"""Add every missing generated secret to .env. Never overwrites a value, never prints one.

Two values cannot be generated and must be pasted in by you: HYPERDX_API_KEY (HyperDX, Team
Settings) and OPENROUTER_API_KEY (openrouter.ai, Keys).
"""

import secrets
import sys
from pathlib import Path

ENV = Path(__file__).resolve().parent.parent / ".env"
FROM_YOU = ("HYPERDX_API_KEY", "OPENROUTER_API_KEY")
GENERATED = {
    "CLICKHOUSE_READER_PASSWORD": lambda: secrets.token_urlsafe(24),
    "CLICKHOUSE_WRITER_PASSWORD": lambda: secrets.token_urlsafe(24),
    "CLICKHOUSE_MCP_AUTH_TOKEN": lambda: secrets.token_urlsafe(32),
    "SRE_MCP_TOKEN": lambda: secrets.token_urlsafe(32),
    "SRE_SESSION_SECRET": lambda: secrets.token_urlsafe(32),
    "SRE_APPROVER_EMAIL": lambda: "oncall@example.com",
    "SRE_APPROVER_PASSWORD": lambda: secrets.token_urlsafe(12),
    "LIBRECHAT_USER_EMAIL": lambda: "sre@example.com",
    "LIBRECHAT_USER_PASSWORD": lambda: secrets.token_urlsafe(12),
    "HYPERDX_USER_EMAIL": lambda: "workshop@example.com",
    "HYPERDX_USER_PASSWORD": lambda: secrets.token_urlsafe(12),
    "JWT_SECRET": lambda: secrets.token_hex(32),
    "JWT_REFRESH_SECRET": lambda: secrets.token_hex(32),
    "CREDS_KEY": lambda: secrets.token_hex(32),
    "CREDS_IV": lambda: secrets.token_hex(16),
}


def read(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    pairs = (line.split("=", 1) for line in path.read_text().splitlines() if "=" in line and line[0] != "#")
    return {key.strip(): value.strip() for key, value in pairs}


def main() -> int:
    current = read(ENV)
    missing = [key for key in GENERATED if not current.get(key)]
    if missing:
        with ENV.open("a") as f:
            f.write("\n# Generated by make env\n")
            for key in missing:
                f.write(f"{key}={GENERATED[key]()}\n")
        print(f"Added {len(missing)} generated values to .env: {', '.join(missing)}")
    absent = [key for key in FROM_YOU if not current.get(key)]
    if absent:
        print(f"Add these to .env yourself, then run the command again: {', '.join(absent)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
